### ISSUE TITLE
custom color in tailwind config file not being recognized 

### ISSUE THREAD

**Issue by vital-tech-results** [marklawlor/tailwindcss-react-native#80] opened 2022-06-18 04:04 UTC
Everything works great on this package. The docs are clear and helpful. I only have one issue. When I add a custom color to ```tailwind.config.js``` it's not registering. I've restarted expo but still doesn't work. This is my config file for tailwind: 

```
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./screens/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "regal-blue": "#50d71e",  // this part is not working
      },
    },
  },
  plugins: [],
};

```

Do you have any suggestions? It's running 
```expo 5.4.11```
```react-native": "0.68.2```
```react": "17.0.2```

**Comment by marklawlor** [comment] 2022-06-18 22:46
Hey @vital-tech-results, can you please run the official Tailwind CLI on your project to generate a .css file to see if it includes your custom colours?

Which version of the library are you using as well?

**Comment by vital-tech-results** [comment] 2022-06-18 23:04
Thanks for the quick reply @marklawlor 

I'm running the following:

```    "nativewind": "^2.0.0-next.10"```
 ```   "tailwindcss": "^3.1.3",```
```    "typescript": "~4.3.5"```

Apologies, I'm not sure what you meant by *"which version of the library"* I am using. I guess you mean your nativewind nom package?

**Comment by vital-tech-results** [comment] 2022-06-18 23:13
I looked at [the official docs](https://tailwindcss.com/docs/installation) but I'm not sure how to build on a react-native project built using expo SDK. I will keep looking. The docs say: 

```npx tailwindcss -i ./src/input.css -o ./dist/output.css --watch```

but this appears to target a single CSS file and output it into a ```dist``` directory. But there are several files using tailwind so I'll need to investigate further on how to output tailwind in a react-native project.

**Comment by marklawlor** [comment] 2022-06-19 04:25
That command is correct. This library converts the CSS generated by the official tool into RN code - so if you don't see your custom class in the .css output then it's not being processed by RN either. 

The `content` option of `tailwind.config.js` controls what classes are being processed. If your colour is not in the .css output it's probably not being included in the content glob

**Comment by vital-tech-results** [comment] 2022-06-19 16:57
I may be confused but my project doesn't have ```.src``` directory. Instead I ran this code in the terminal in VS Code: 

```
npx tailwindcss -i ./screens/* -o ./dist/output.css
```

I replaced ```src``` with ```screens``` and used ```*``` to indicate everything in the ```screens``` directory. 

However, I don't see a file called ```output.css``` in my ```dist``` directory.

Attached is a screenshot of my project structure.

Thank you,

DJ

![share_Inspiration_today_2022-06-18@2x](https://user-images.githubusercontent.com/1271949/174491862-48fe8415-d10e-45fd-9cc5-4f481d1cbf24.png)

**Comment by marklawlor** [comment] 2022-06-19 22:38
@vital-tech-results Let's take a couple of steps back and do troubleshooting 101: Does it work in a Hello World example.

Can you please follow the instructions in the quick start guide to create a new project with your custom color. If this *doesn't work* can you please post that code in a public repo.

If it does work, the only difference between the Hello World example and your main project should be the `content` setting of your `tailwind.config.js`. You can read more about that setting on the Tailwind CSS website https://tailwindcss.com/docs/content-configuration.

If your content is not correct, Tailwind CSS will not work - hence this library will not work.

In the examples I use `./src/**.*` as an example of a content string because this is a common project folder structure and how the Tailwind CSS documentation is written. It's not a requirement to have a `src` directory, and if your folder structure is different, then you need to customise the `content` option to match your folder structure.

**Comment by marklawlor** [comment] 2022-06-21 04:33
Thanks for the support :100: 

I'm going to close this issue as there doesn't appear to be an issue with custom colors, but you can still respond with questions if you need help debugging.

**Closed by marklawlor** 2022-06-21 04:33 UTC

**Comment by fikkatra** [comment] 2022-07-26 11:55
@vital-tech-results did you find what the problem was in your code? Running into the same issue.

**Comment by vital-tech-results** [comment] 2022-07-26 12:27
Yes, I had to modify the ```content``` setting in the ```tailwind.config.js``` file. 

Just like @marklawlor  mentioned: 

If it does work, the only difference between the Hello World example and your main project should be the content setting of your ```tailwind.config.js```. You can read more about that setting on the Tailwind CSS website https://tailwindcss.com/docs/content-configuration.

If your content is not correct, Tailwind CSS will not work - hence this library will not work.

In the examples I use ```./src/**.*``` as an example of a content string because this is a common project folder structure and how the Tailwind CSS documentation is written. It's not a requirement to have a src directory, and if your folder structure is different, then you need to customise the content option to match your folder structure.

**Comment by fikkatra** [comment] 2022-07-26 13:33
Checked and double checked the config, I'm sure the right files are included. Since it's working for you, I'm sure it must be something on my side. But the strange thing is, if I switch back to using the `tailwindcss-react-native` package, using the exact same code and config (apart from adding the TailwindProvider), it works.

To clarify, with 'it doesn't work' I mean that when I define a custom color 'primary', and add the className `text-primary` on a Text component, it doesn't have any effect. With `tailwindcss-react-native` however, I see the text displaying in the primary color.

**Comment by marklawlor** [comment] 2022-07-26 14:24
@fikkatra Can you publish a repo with a demonstration of your issue, I cannot replicate it on a new project.

Changing between `tailwindcss-react-native` and `nativewind` shouldn't matter as both just use Tailwind's compiler to process your theme.

You can test your projects configuration directly with Tailwind CLI. Run `npx tailwind -o test.css` and then open `test.css` and inspect the generated css for your custom color. If it didn't then you have a configuration issue with your project.

**Comment by fikkatra** [comment] 2022-07-26 15:34
@marklawlor thanks a lot for looking into it. Here's a minimal repro: https://github.com/fikkatra/nativewind-repro

I can confirm that `test.css` contains the class `.text-primary` after running `npx tailwind -o test.cs`s. This was expected, as I use the exact same config as I do when using `tailwindcss-react-native`, so I believe this config is correct. The only problem is applying `text-primary` as a className, which doesn't seem to have any effect.

**Comment by marklawlor** [comment] 2022-07-26 17:56
@fikkatra Can you try version `2.0.0-next.53` - I forgot that `DEFAULT` was a valid tailwind config option and it was interfering with the [platform themes](https://www.nativewind.dev/customization/theme#per-platform-theme-values).

**Comment by crstnmac** [comment] 2022-08-06 15:55
> @vital-tech-results did you find what the problem was in your code? Running into the same issue.

Same here

**Comment by crstnmac** [comment] 2022-08-06 15:56
> @fikkatra Can you try version `2.0.0-next.53` - I forgot that `DEFAULT` was a valid tailwind config option and it was interfering with the [platform themes](https://www.nativewind.dev/customization/theme#per-platform-theme-values).

Using the mentioned version. Stil same issue.

**Comment by marklawlor** [comment] 2022-08-06 16:18
Instead of commenting "same here" can you please share either your `tailwind.config.js` or your repo. This issue should be resolved, so if it's still occuring then I need more information.

**Comment by crstnmac** [comment] 2022-08-06 16:24
> Instead of commenting "same here" can you please share either your `tailwind.config.js` or your repo. This issue should be resolved, so if it's still occuring then I need more information.

My apologies, I edited the comment.

**Comment by crstnmac** [comment] 2022-08-07 15:41
Custom colors worked after hard cleaning the proj

For Windows
```
del %appdata%\Temp\react-native-* & cd android & gradlew clean & cd .. & del node_modules/ & npm cache clean --force & npm install & npm start -- --reset-cache
```

**Comment by fikkatra** [comment] 2022-08-09 13:19
> @fikkatra Can you try version `2.0.0-next.53` - I forgot that `DEFAULT` was a valid tailwind config option and it was interfering with the [platform themes](https://www.nativewind.dev/customization/theme#per-platform-theme-values).

I can confirm that with version `2.0.0-next.53`, custom colors and their util classes work. Thanks a lot @marklawlor !

**Comment by chaosLegacy** [comment] 2022-09-05 21:54
Is there a way to import the colors from a typescript file into tailwind.config.js?
I already added 
/** @type {import('tailwindcss').Config} */
to support types but my inteliiSense crashes Tailwind CSS: Can't resolve './src/constants/colors'

Here is my colors.ts file
`export const Colors = {
  blue: {
    light: '#ECEDF7',
    DEFAULT: '#212A85',
  },
  green: {
    light: '#EDFFFE',
    DEFAULT: '#02B6A9',
  },
  red: {
    light: '#FDE2DE',
    DEFAULT: '#F3705A',
  },
  yellow: {
    light: '#FFFAE9',
    DEFAULT: '#FFD15C',
  },
  grey: {
    lightest: '#F8F9FB',
    button: '#F0F1F5',
    medium: '#CED0DF',
    light: '#c3c9da',
    DEFAULT: '#83869A',
    ripple: 'rgba(50, 50, 50, 0.1)',
  },
  black: {
    darkest: '#000000',
    DEFAULT: '#414458',
  },
  white: '#FFFFFF',
  transparent: 'transparent',
  orange: {
    DEFAULT: '#FD7A02',
  },
};
`

And here is my tailwind.config.js

`/** @type {import('tailwindcss').Config} */

const { Colors } = require('./src/constants/colors');
const brandTheme = require('./src/constants/theme');
module.exports = {
  darkMode: 'class',
  content: [
    "./App.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}"
  ],
  theme: {
    extend: {
      // ...brandTheme,
      colors: {
        primary: Colors.green
      },
    },
  },
  plugins: [],
}`

It works for importing .js file like brandTheme for example but not typescript, now I need the same code of my colors inside tailwind.config.js and colors.ts to bypass this error

**Comment by marklawlor** [comment] 2022-09-05 22:00
No, Tailwind CSS only understands `.js` files.

If you'd like types in your colors file, just add them via comments https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html

**Comment by chaosLegacy** [comment] 2022-09-09 11:55
Thank you for your answer, is there a way to make my color.js readable in my typescript project?
I've addedd 
```
    "allowJs": true,
    "checkJs": false,
```
in my `tsconfig.json`
I tried with 
```
const theme = require('~/constants/theme');
import * as theme from ('~/constants/theme');
```

my theme.js file look like this

```
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck
module.exports = {
  colors: {
    primary: {
      50: '#f4f5f9',
      100: '#dec9e9',
      200: '#dac3e8',
      300: '#c19ee0',
      400: '#b185db',
      500: '#a06cd5',
      600: '#9163cb',
      700: '#815ac0',
      800: '#7251b5',
      900: '#6247aa',
      DEFAULT: '#a06cd5',
    }
  },
};
```
but my project keep crashing
<img width="315" alt="Screenshot 2022-09-09 at 13 53 05" src="https://user-images.githubusercontent.com/11313734/189344029-73de3afc-fb9f-4d9e-b6ba-cb254bb8d2de.png">
any idea how to fix this 🙏

**Comment by marklawlor** [comment] 2022-09-09 21:24
https://www.typescriptlang.org/tsconfig#resolveJsonModule

**Comment by marklawlor** [comment] 2022-09-09 21:26
https://www.nativewind.dev/guides/theme-values

**Comment by chaosLegacy** [comment] 2022-09-10 09:43
@marklawlor really appreciate your help, but I'm not able to make it work as I can't import .js files into my projects,

```
// HomeScreen.tsx
import colors from "./colors";

export function MyActivityIndicator(props) {
  return <ActivityIndicator size="small" color={colors.tahiti.500} {...props} />;
}
```
I keep getting the same error as above

```
// HomeScreen.tsx
import resolveConfig from 'tailwindcss/resolveConfig'
import tailwindConfig from './tailwind.config.js'

const fullConfig = resolveConfig(tailwindConfig)
```
<img width="315" alt="Screenshot 2022-09-10 at 11 41 22" src="https://user-images.githubusercontent.com/11313734/189477883-9453057d-5e28-4d59-b200-fcd5914573ed.png">

Do I need to make extra changes in my babel.config.js or tsconfig.json?

**Comment by marklawlor** [comment] 2022-09-10 10:00
Your importing `import tailwindConfig from './tailwind.config.js'`, which means Metro is looking for a file called `tailwind.config.js.js`. 

Unless you are using ESM, you do not include the file extension when importing files.

**Comment by chaosLegacy** [comment] 2022-09-10 10:32
Still not working, when removing the file extension as you mentioned 
import tailwindConfig from './tailwind.config'
I started getting the same error as the first time

```
Unexpected token (. import call expects exactly
one argument.
Unexpected token ". import call expects exactly
one argument.
no stack
no stack
```

**Comment by marklawlor** [comment] 2022-09-10 11:14
This doesn't appear to be an issue with NativeWind, an unfortunately I do not have the capacity to debug your project.

I would recommend following simple troubleshooting:
- can you import other js files
- does the same problem occur when creating a new project

Then you can use simple isolation techniques to find your cause.

**Comment by wizevlad** [comment] 2022-10-10 18:08
[this](https://github.com/marklawlor/nativewind/issues/80#issuecomment-1195639568) is also happening on version 2.011 @marklawlor

**Comment by marklawlor** [comment] 2022-10-10 23:19
@wizevlad Please provide a code example. This issue has been resolved, all other reports I have received have been human error
